#!/bin/bash 

function compress {
    brass data/$1.txt data/$1.bin
    data/lz48 -i data/$1.bin -o data/$1.binlz
    rm data/$1.bin
}

if [ -z "$1" ]; then
    compress title
    compress end
    compress lvl1
    compress lvl2
    compress lvl3
    compress lvl4
fi

brass -s bom5.asm bom5.rom -l bom5.html
